name: scrramble_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.11.12
  - colorama=0.4.6
  - contourpy=1.3.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - expat=2.6.4
  - fontconfig=2.14.1
  - fonttools=4.56.0
  - freetype=2.12.1
  - gh=2.67.0
  - glib=2.78.4
  - glib-tools=2.78.4
  - icu=73.1
  - joblib=1.5.2
  - jpeg=9e
  - kiwisolver=1.4.7
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.12.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libiconv=1.18
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libopenblas=0.3.29
  - libpng=1.6.39
  - libpq=17.2
  - libprotobuf=4.25.3
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxkbcommon=1.8.0
  - libxml2=2.13.5
  - libxslt=1.1.41
  - lz4-c=1.9.4
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - minizip=4.0.3
  - munkres=1.1.4
  - mysql=8.4.0
  - ncurses=6.4
  - nspr=4.36
  - nss=3.89.1
  - numpy=2.2.3
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.6.0
  - packaging=24.2
  - pandas=2.2.3
  - patsy=1.0.1
  - pcre2=10.42
  - pillow=11.1.0
  - pip=25.0
  - pthread-stubs=0.4
  - pyparsing=3.2.1
  - pyside6=6.7.2
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.1
  - python_abi=3.11
  - pytz=2024.1
  - qhull=2020.2
  - qtbase=6.7.2
  - qtdeclarative=6.7.2
  - qtshadertools=6.7.2
  - qtsvg=6.7.2
  - qttools=6.7.2
  - qtwebchannel=6.7.2
  - qtwebengine=6.7.2
  - qtwebsockets=6.7.2
  - readline=8.2
  - scikit-learn=1.7.2
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.8.0
  - six=1.17.0
  - sqlite=3.45.3
  - statsmodels=0.14.4
  - threadpoolctl=3.6.0
  - tk=8.6.14
  - tornado=6.4.2
  - tqdm=4.67.1
  - tzdata=2025a
  - unicodedata2=16.0.0
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-renderutil=0.3.10
  - xkeyboard-config=2.43
  - xorg-libx11=1.8.11
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.1
      - aiofiles==25.1.0
      - array-record==0.8.3
      - astunparse==1.6.3
      - attrs==25.4.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - chex==0.1.91
      - dm-tree==0.1.9
      - docstring-parser==0.17.0
      - einops==0.8.1
      - etils==1.13.0
      - flatbuffers==25.9.23
      - flax==0.12.1
      - fsspec==2025.12.0
      - gast==0.7.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.72.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - humanize==4.14.0
      - idna==3.11
      - immutabledict==4.2.2
      - importlib-resources==6.5.2
      - jax==0.8.1
      - jax-cuda12-pjrt==0.8.1
      - jax-cuda12-plugin==0.8.1
      - jaxlib==0.8.1
      - keras==3.12.0
      - libclang==18.1.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - msgpack==1.1.2
      - namex==0.1.0
      - nest-asyncio==1.6.0
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cuda-cupti-cu12==12.9.79
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.9.86
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cudnn-cu12==9.17.0.29
      - nvidia-cufft-cu12==11.4.1.4
      - nvidia-cusolver-cu12==11.7.5.82
      - nvidia-cusparse-cu12==12.5.10.65
      - nvidia-nccl-cu12==2.28.9
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvshmem-cu12==3.4.5
      - opt-einsum==3.4.0
      - optax==0.2.6
      - optree==0.18.0
      - orbax-checkpoint==0.11.30
      - promise==2.3
      - protobuf==6.33.2
      - psutil==7.1.3
      - pyarrow==22.0.0
      - pygments==2.19.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - rich==14.2.0
      - scrramble==0.1.0
      - simple-parsing==0.1.7
      - simplejson==3.20.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - tensorflow-datasets==4.9.9
      - tensorflow-metadata==1.17.2
      - tensorstore==0.1.79
      - termcolor==3.2.0
      - toml==0.10.2
      - toolz==1.1.0
      - treescope==0.1.10
      - typing-extensions==4.15.0
      - urllib3==2.6.1
      - werkzeug==3.1.4
      - wrapt==2.0.1
      - zipp==3.23.0
prefix: /local_disk/vikrant/miniconda3/envs/scrramble_env
